import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "./Providers";

export const metadata: Metadata = {
  title: "교보문고_임수경",
  icons: {
    icon: "favicon.ico",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className="text-base w-screen h-screen">
          <Header />
          <main className="mt-[180px] h-full">{children}</main>
        </body>
      </html>
    </Providers>
  );
}
