import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "./Providers";

export const metadata: Metadata = {
  title: "교보문고_임수경",
  icons: {
    icon: "favicon.ico",
  },
  description: "Generated by create next app",
};

const notoSansKR = Noto_Sans_KR({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={`${notoSansKR.variable} text-base w-screen h-screen`}>
          <Header />
          <main className="h-full lg:mt-[50px] xl:mt-[50px]">{children}</main>
        </body>
      </html>
    </Providers>
  );
}
