import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "교보문고_임수경",
  icons: {
    icon: "favicon.ico",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-base">
        <Header />
        <main className="mt-[180px]">{children}</main>
      </body>
    </html>
  );
}
